sudo: required
services:
  - docker

before_install:
  - docker build -t fcarbah/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run fcarbah/react-test npm run test -- --coverage

after_success:
  - docker build -t fcarbah/multi-client ./client
  - docker build -t fcarbah/multi-nginx ./nginx
  - docker build -t fcarbah/multi-server ./server
  - docker build -t fcarbah/multi-worker ./worker

#login to docker cli in other to push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take these images and push them to docker hub
  - docker push fcarbah/multi-client
  - docker push fcarbah/multi-nginx
  - docker push fcarbah/multi-server
  - docker push fcarbah/multi-worker

#deploy to hosting -- we are using amazon elasticbeanstalk
deploy:
  #all of these come from amazon aws elastic beanstalk
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-dockerapp"
  env: "MultiDockerapp-env"
  bucket_name: "elasticbeanstalk-us-west-2-184721162578"
  bucket_path: "multi-dockerapp" #same as app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
